@url=http://localhost:3000/v1
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJnb3BoZXJzb2NpYWwiLCJleHAiOjE3NTY4NDE4NTUsImlhdCI6MTc1NjU4MjY1NSwiaXNzIjoiZ29waGVyc29jaWFsIiwibmJmIjoxNzU2NTgyNjU1LCJzdWIiOjM2fQ.h8mI8P0QgBWg38TGtol99NqXey8Zr5xCXtGaZfdQQCQ

###
POST {{url}}/auth/token
Content-Type: application/json

{
  "email": "nena11@gmail.com",
  "password": "122@233"
}

###
GET {{url}}/health

###
POST {{url}}/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Teste 3",
  "content": "Teste 3",
  "tags": ["teste1, teste2"]
}

###
GET {{url}}/posts/2

###
GET {{url}}/users/1

###
GET {{url}}/users/feed

###
POST {{url}}/auth/register
Content-Type: application/json

{
  "username": "nenaporto11",
  "email": "nena11@gmail.com",
  "password": "122@233"
}

###
PUT {{url}}/users/activate/45b10a6b-0d7c-4336-b802-ef4a983a3667