@url=http://localhost:3000/v1

###
GET {{url}}/health

###
POST {{url}}/posts
Content-Type: application/json

{
  "title": "Teste 2",
  "content": "Teste 2",
  "tags": ["teste1, teste2"]
}

###
GET {{url}}/posts/2

###
GET {{url}}/users/1

###
GET {{url}}/users/feed

###
POST {{url}}/auth/register
Content-Type: application/json

{
  "username": "nenaporto11",
  "email": "nena11@gmail.com",
  "password": "122@233"
}

###
PUT {{url}}/users/activate/45b10a6b-0d7c-4336-b802-ef4a983a3667